### ISSUE TITLE
Unexpected token v in WOF geojson

### ISSUE THREAD

**Issue by easherma** [pelias/whosonfirst#103]
> wof_data//data/856/333/45/85633345.geojson: SyntaxError: Unexpected token v

I think this may be an issue for the WOF directly, but figured I'd post it here first.

**Comment by trescube** [comment]
That's actually a git issue.  That record is particularly troublesome since it's the country of New Zealand.  The coastline polygon for New Zealand is quite large and eclipses the 100MB standard git file size limit so you'll need to use git-lfs to grab that file.  Please see: https://github.com/whosonfirst/whosonfirst-data#git-and-large-files for resolution

**Comment by trescube** [comment]
If you look at that local file as it stands now, you'll see that it's just a short message about git-lfs and not geojson.

**Comment by orangejulius** [comment]
And also, I believe @trescube has added error handling such that WOF will just skip records when it can't parse the json, rather than crash completely, so if you are ok with New Zealand being missing, you can allow the import to continue.

**Comment by trescube** [comment]
@easherma did you get this issue resolved via git-lfs?

**Comment by easherma** [comment]
@trescube For my use case, I'm only concerned with the USA, so I ignored the error. More detailed description of the issue in the error would've prevented me from opening the issue. :-)

**Comment by trescube** [comment]
Closed via #105
