### ISSUE TITLE
friendlier error messages for the deprecated config var 'adminLookup'

### ISSUE THREAD

**Issue by missinglink** [pelias/whosonfirst#210]
I ran `npm run download` today with the same config I've been using for a long time and I got the following error:

```
/var/www/pelias/whosonfirst/node_modules/pelias-config/index.js:28
        throw new Error(err.details[0].message);
        ^

Error: "adminLookup" is not allowed
    at /var/www/pelias/whosonfirst/node_modules/pelias-config/index.js:28:15
    at _validateWithOptions (/var/www/pelias/whosonfirst/node_modules/joi/lib/any.js:654:20)
    at root.validate (/var/www/pelias/whosonfirst/node_modules/joi/lib/index.js:121:23)
    at Object.deep [as generate] (/var/www/pelias/whosonfirst/node_modules/pelias-config/index.js:26:9)
    at Object.<anonymous> (/var/www/pelias/whosonfirst/src/bundleList.js:9:49)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

If we are removing support for the `imports.whosonfirst.adminLookup` property it would be nice to give users a more informative message such as:

> "The imports.whosonfirst.adminLookup property has been deprecated in favor of a global property xxx.xxx. See PR #xxx for more details."

**Comment by trescube** [comment]
I'm confused.  The whosonfirst importer never had support for `adminLookup` from the config since it's, well, whosonfirst and doesn't use adminLookup.  When's the last time you ran the WOF importer?  The schema (which has been around in some form since [late December](https://github.com/pelias/whosonfirst/pull/182/files#diff-21a7636e3b90c71c997364279e9a78b6)) disallows unknown child properties for `imports.whosonfirst` which is what you're running into.  

Other importers that do use `adminLookup` don't explicitly reject the importer-level `adminLookup` property but do provide a warning about relocation:

- [OpenAddresses](https://github.com/pelias/openaddresses/blob/master/import.js#L39-L42)
- [OpenStreetMap](https://github.com/pelias/openstreetmap/blob/master/index.js#L5-L8)
- [Geonames](https://github.com/pelias/geonames/blob/master/import.js#L5-L8)

**Comment by missinglink** [comment]
:+1: closing
