### ISSUE TITLE
Resumable import?

### ISSUE THREAD

**Issue by Binternet** [pelias/whosonfirst#335]
If the import process has stopped and i'm re-running it, will it resume? or if i'm running an import and the data already exists, will it skip it or override everything?

**Comment by orangejulius** [comment]
Hey @Binternet,
There isn't resume functionality in any of our importers currently. Re-starting an importer with the same data will re-start from the beginning. Elasticsearch will handle that without issue. However if you were, say, updating data to a newer copy, you would want to delete the Elasticsearch index and start over.

For the Who's on First importer in particular, resume functionality wouldn't be super helpful, since it doesn't take very long to run. But the other importers do, so some sort of resume functionality would really help. I'm happy to discuss ideas for an implementation of that.

**Comment by Binternet** [comment]
Well, i'm not that of an expert in nodejs but the easiest solution that comes to mind is to have a `import-state` file which holds the current index count and once the importer starts it will check if we have a `import-state` file and resume from that point. sounds reasonable?

**Comment by orangejulius** [comment]
That definitely sounds reasonable. I suspect for importers that handle multiple files, we would want to include a filename and record number to record how far it's progressed.

**Comment by kylebarron** [comment]
> Elasticsearch will handle that without issue

That means that it won't duplicate the data already in elasticsearch, right?

**Comment by orangejulius** [comment]
@kylebarron. Correct. From the perspective of the query the data will be overwritten with an identical copy. So there won't be duplicate records. However it's slightly less efficient as internally elasticsearch handles overwrites by creating a new record, marking it as version 2, and marking the original, version 1 record as deleted.

So for that reason if you're doing a big import and you need max performance its best to start from a clean index.

**Comment by kylebarron** [comment]
Thanks!

**Comment by Binternet** [comment]
@orangejulius so import state could be a `import-state.json` file which holds:

```
{
	import: {
		'filename': 1000,
		'filename2': 2000
	}
}
```

This can support both single/multiple files importers.

**Comment by orangejulius** [comment]
That would be sufficient. I think all of our importers have a deterministic order of processing files, so we could actually get by with storing only one filename at a time, as well as the progress within that file.

We already have several places in the code where a function is called to check into the progress of the import every few seconds (most notably in dbclient), so it is also advantageous if the import-state can be generated from a single moment in time rather than having to look at past progress.

Another important requirement of the implementation would be that the import-state file is removed when the importer completes successfully.

**Comment by Binternet** [comment]
Not so sure I got your first point, but as if I recall correctly theres an output of `[dbclient] imported X records..` to the console when it finishes a file or a batch, that is the spot that the import-state file should be updated as far as I can see it.

Regarding the import-state removal upon completion, that's a must.

**Comment by orangejulius** [comment]
Lets say you have 10 files of 100 lines each. You could store
```
{
'file1': 100,
'file2': 100,
'file3': 50
}
```

To signify having completed the first two files and being half way through the 3rd. But assuming that the files are always processed in the same order, I think

```
{
'file3': 50
}
```

contains the same amount of information.

The ouput from `dbclient` is the right pattern to follow (I think), but not the right place for this to live. I think each importer would have to handle this, since each one processes files differently.

**Comment by Binternet** [comment]
Oh, for sure once you finish with a file you don't need to specify it in the import-state file, only the file that is currently being processed (hence 'last touched')

**Comment by orangejulius** [comment]
Yeah. I think the openaddresses importer is the one to best try this out on, since it already has [some code](https://github.com/pelias/openaddresses/blob/master/lib/streams/recordStream.js#L47-L49) to run something periodically.

**Comment by orangejulius** [comment]
While I think it would be possible, I don't think we should do any work to support resumable imports in the near future.

With proper configuration, it's possible to do a complete Elasticsearch build in under 16 hours now, and adding the complexity of resume support would be a significant maintenance going forward.

If someone _really_ wants this, please let us know. But at this time we don't plan to support it.
