### ISSUE TITLE
problem with filter for download 

### ISSUE THREAD

**Issue by ticxx** [pelias/whosonfirst#430]
hey,
We set 102191581 for Europe in pelias.json.
The importer downloads the whole world ...
any help?
thanks stefan

**Comment by missinglink** [comment]
This is the expected behaviour, WhosOnFirst do not provide 'extracts' like openstreetmap do.

So it requires downloading the while planet file to get access to the records you need.

The `importPlaces` property will ensure that you don't end up importing all that data in to your elasticsearch index.

**Comment by zifeo** [comment]
@missinglink @orangejulius if https://github.com/pelias/whosonfirst/blob/master/utils/download_data.js#L12 was offered as an option, would it a way of implement this behaviour?

**Comment by orangejulius** [comment]
@zifeo it would not be quite that simple, but the country bundles are a recent development, and we should consider using them to allow for smaller downloads. I just opened https://github.com/pelias/whosonfirst/issues/459 to track this.
