### ISSUE TITLE
download only whosonfirst-data-latest.db

### ISSUE THREAD

**Issue by tadjik1** [pelias/whosonfirst#437]
Hi there,
I'm working currently on infrastructure for pip-service and it requires sqlite dump to be downloaded first. It turns out that this module downloads more than 150 dbs from dist.whosonfirst, even though later during pip-service start only 1 main file `whosonfirst-data-latest.db` is used. Is there a way to download only 1 file contains all data and not all of them?

ref: https://github.com/pelias/wof-admin-lookup/blob/master/src/pip/readStream.js#L21

**Comment by orangejulius** [comment]
Hey @tadjik1~

The [download script](https://github.com/pelias/pip-service/blob/master/bin/download) in the pip-service is configured to only download administrative data, so it should download only the file you need.

Have you given that one a try? If it downloads extra data, we want to know about it, since that's the whole point of that script.

**Comment by missinglink** [comment]
Are the other 149 databases for postcodes?

If the config setting `imports.whosonfirst.importPostalcodes` is set to `true` (defaults to `false`) then I believe they will be included in the list of files to download.

Postcodes are not loaded in to PIP, although there is a long discussion about why that it the case, I won't go in to detail here.

The postcodes are imported in to elasticsearch under the `postcode` layer.
